"""add access_token to user

Revision ID: 010787b0d710
Revises: a3b84eaf97c2
Create Date: 2026-07-09 12:52:28.731829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010787b0d710'
down_revision = 'a3b84eaf97c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###
